server:
  port: 7000

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

  redis:
    url: ${REDIS_URL}

  rabbitmq:
    addresses: ${CLOUDAMQP_URL}

  redis:
    url: ${REDIS_URL}

  rabbitmq:
    host: ${AMQP_HOST}
    username: ${AMQP_USERNAME}
    password: ${AMQP_PASSWORD}
    port: 5671
    ssl:
      enabled: false

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update

telegram:
  bot:
    token: ${BOT_TOKEN}
    username: ${BOT_NAME}
    domain: ${APP_DOMAIN}
    api: ${WEBHOOK_PATH}
    first-question-id: 1
    messages:
      stopMessage:
        text: Your active request cancelled!
        textAz: Sizin aktiv sorğunuz dayandırıldı.
        textRu: Ваш активный запрос отменен!
      agencyInformed:
        text: "Your contact info sent to %s agency."
        textAz: "Sizin əlaqə məlumatlarınız %s agentliyinə yollandı."
        textRu: "Ваша контактная информация отправлена в агентство %s."
      loadMore:
        text: Load more.
        textAz: Daha çox yüklə.
        textRu: Загрузи больше.
      loadMoreMessage:
        text: "You have %d more offers."
        textAz: "Sizin daha %d təklifiniz var."
        textRu: "У вас есть еще %d предложений."
      sendContact:
        text: Yes, send my contact info.
        textAz: Bəli, şəxsi məlumatlarım yollanılsın.
        textRu: Tercumeye ehtiyac var.
      sendContactCancel:
        text: No, agency should contact me via telegram.
        textAz: Xeyir, agentlik yalnız telegram vasitəsi ilə əlqə qursun.
        textRu: Нет, агентство должно связаться со мной по телеграмме.
      sendContactEdit:
        text: I have changed my number.
        textAz: Telefon nömrəmi dəyişdirmişəm.
        textRu: Я поменял свой номер.
      saveAndSendContact:
        text: Yes, save and send my contact info.
        textAz: Bəli, əlaqə məlumatlarımı yadda saxla və yolla.
        textRu: Да, сохраните и отправьте мою контактную информацию.
      sendContactMessage:
        text: "Do you want to accept %s's offer?"
        textAz: "%s agentliyinin təklifini qəbul etmək istəyirsinizmi?"
        textRu: "Вы хотите принять предложение %s?"