server:
  port: 7000

spring:
  datasource:
    url: jdbc:postgresql://192.168.0.100:5432/tour
    username: postgres
    password: 3262015Aze3262!

  redis:
    url: ${REDIS_URL}

  rabbitmq:
    addresses: ${CLOUDAMQP_URL}

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update

telegram:
  bot:
    token: 1807237865:AAGvhr1CW_yk5FEzfjgWNthALwHC_0yCX-8
    username: CodeAcademyBot
    domain: customtelegrambit.herokuapp.com
    api: /api/v1/webhook
    first-question-id: 1
    messages:
      stopMessage:
        text: Your active request cancelled!
        textAz: Sizin aktiv sorğunuz dayandırıldı.
        textRu: Ваш активный запрос отменен!
      agencyInformed:
        text: "Your contact info sent to %s agency."
        textAz: "Sizin əlaqə məlumatlarınız %s agentliyinə yollandı."
        textRu: "Ваша контактная информация отправлена в агентство %s."
      loadMore:
        text: Load more.
        textAz: Daha çox yüklə.
        textRu: Загрузи больше.
      loadMoreMessage:
        text: "You have %d more offers."
        textAz: "Sizin daha %d təklifiniz var."
        textRu: "У вас есть еще %d предложений."
      sendContact:
        text: Yes, send my contact info.
        textAz: Bəli, şəxsi məlumatlarım yollanılsın.
        textRu: Tercumeye ehtiyac var.
      sendContactCancel:
        text: No, agency should contact me via telegram.
        textAz: Xeyir, agentlik yalnız telegram vasitəsi ilə əlqə qursun.
        textRu: Нет, агентство должно связаться со мной по телеграмме.
      sendContactEdit:
        text: I have changed my number.
        textAz: Telefon nömrəmi dəyişdirmişəm.
        textRu: Я поменял свой номер.
      saveAndSendContact:
        text: Yes, save and send my contact info.
        textAz: Bəli, əlaqə məlumatlarımı yadda saxla və yolla.
        textRu: Да, сохраните и отправьте мою контактную информацию.
      sendContactMessage:
        text: "Do you want to accept %s's offer?"
        textAz: "%s agentliyinin təklifini qəbul etmək istəyirsinizmi?"
        textRu: "Вы хотите принять предложение %s?"