server:
  port: 7000

spring:
  datasource:
    url: jdbc:postgresql://192.168.0.100:5432/tour
#    url: jdbc:postgresql://localhost:5432/tour
    username: postgres
    password: 3262015Aze3262!
    driver-class-name: org.postgresql.Driver

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update

telegram:
  bot:
    token: 1807237865:AAGvhr1CW_yk5FEzfjgWNthALwHC_0yCX-8
    username: CodeAcademyBot
    domain: customtelegrambit.herokuapp.com
    api: /api/v1/webhook
    first-question-id: 1
    messages:
      stopMessage:
        text: Your active request cancelled!
        textAz: Sizin aktiv sorğunuz dayandırıldı.
        textRu: Ваш активный запрос отменен!
      loadMore:
        text: Load more.
        textAz: Daha çox yüklə.
        textRu: Tercumeciye ehtiyac var.
      loadMoreMessage:
        text: "You have %d more offers."
        textAz: "Sizin daha %d təklifiniz var."
        textRu: "%d tercumeciye ehtiyac var."
      sendContact:
        text: Yes, send my contact info.
        textAz: Bəli, şəxsi məlumatlarım yollanılsın.
        textRu: Tercumeye ehtiyac var.
      sendContactCancel:
        text: No, agency should contact me via telegram.
        textAz: Xeyir, agentlik yalnız telegram vasitəsi ilə əlqə qursun.
        textRu: We don't have translator. What did you expect?
      sendContactEdit:
        text: I have changed my number.
        textAz: Telefon nömrəmi dəyişdirmişəm.
        textRu: I really need a translator.
      saveAndSendContact:
        text: Yes, send and save my contact info.
        textAz: Bəli, şəxsi məlumatlarım yolla və yadda saxlaya.
        textRu: Tercumeye ehtiyac var.
      sendContactMessage:
        text: "Do you want to accept %s's offer?"
        textAz: "%s agentliyinin təklifini qəbul etmək istəyirsinizmi?"
        textRu: "%s tercumeye ehtiyac var."