server:
  port: 7000

spring:
  datasource:
    url: jdbc:postgresql://192.168.0.100:5432/tour
#    url: jdbc:postgresql://localhost:5432/tour
    username: postgres
    password: 3262015Aze3262!
    driver-class-name: org.postgresql.Driver

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update

telegram:
  bot:
    messages:
      stopMessage:
        text: Your active request cancelled!
        textAz: Sizin aktiv sorğunuz dayandırıldı.
        textRu: Ваш активный запрос отменен!
      loadMore:
        text: Load more.
        textAz: Daha çox yüklə.
        textRu: Tercumeciye ehtiyac var.
      loadMoreMessage:
        text: "You have %d more offers."
        textAz: "Sizin daha %d təklifiniz var."
        textRu: "%d tercumeciye ehtiyac var."
      acceptOffer:
        text: Yes, send my contact info.
        textAz: Bəli, şəxsi məlumatlarım yollanılsın.
        textRu: Tercumeye ehtiyac var.
      acceptOfferMessage:
        text: "Do you want to accept %s's offer?"
        textAz: "%s agentliyinin təklifini qəbul etmək istəyirsinizmi?"
        textRu: "%s tercumeye ehtiyac var."
